name: Auto Update package-lock.json for Dependabot

permissions:
  contents: write

on:
  pull_request:
    branches: [main]  # or your default branch
    types: [opened, synchronize]

jobs:
  fix-lockfile:
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies and update lockfile
        run: npm install --package-lock-only

      - name: Commit updated lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "chore: update package-lock.json after dependabot upgrade" || echo "No changes"
          git push
